carlfsmithiii/kwitter

src/index.js
src/reducers/index.js

added Provider and BrowserRouter components to src/index.js, added rootReducer to src/reducers/index.js, created redux store in src/index.js

redux initialization

---

package-lock.json
package.json

material-ui added to package dependencies.

installed @material-ui/core

---

src/reducers/index.js

capitalized Reducers directory

spelling change

---

src/Components/Kweet.js
src/Components/KweetList.js

This is basic.  State is still not 100% correct.

feed is populating with kweets

---

src/Components/App.js
src/Components/LoginRegistration/Login.js
src/index.js

Redirects using history.push.  history is passed multiple times as props.  This doesn't seem the best way to do it.

login redirects.

---

src/Components/App.js
src/Components/LoginRegistration/Login.js

If the user isn't logged in, the user is routed to the log in page.  If the user is logged in, they see the main page.

main page defaults to login unless user logged in

---

src/Components/UserList.js

to correct error from styling Fragment (forbidden!)

changed fragment to div

---

src/Components/App.js
src/Components/LoginRegistration/Login.js
src/index.js

changed away from using history and instead use <Redirect /> component

corrected routing issues in login page

---

src/Components/App.js
src/Components/User.js
src/Components/UserList.js
src/Components/UserPage.js
src/Components/index.js
src/index.js

This is very basic styling.
I also created a UserPage component to route to on click.  We will have to flesh this out.

basic UserListItems styling and onClick redirects to UserPage

---

src/ActionCreators/actions.js
src/Components/App.js
src/Components/KweetList.js
src/Reducers/MessagesReducer.js

There are 2 major problems with this
1) The API currently does not facilitate loading the 20 newest posts.  This current implementation starts with the 20 newest
2) updating on scrolling will require that the kweet list gets the full height of the page, which is currently not the case in the mobile version.  It is my belief that the mobile version should be changed, with the user list going to a side menu.

infinite scrolling

---

src/ActionCreators/actions.js
src/Components/App.js
src/Components/Kweet.js
src/Components/KweetList.js
src/Reducers/MessagesReducer.js

Delete button only shows on loggen in users messages.
Delete button removes from API and state.
There is no confirmation page.

25 delete kweet

---

src/Components/LoginRegistration/Registration.js

this may have merge conflicts...

registration redirects to login

---

src/Components/App.js
src/Components/KweetList.js

This corrects the filter for the kweets on the user page

correct message list when filtered

---

src/Components/App.js
src/Components/Nav.js

home button redirects.  all code is contained to Nav component

---

public/index.html
src/Components/LoginRegistration/Login.js
src/Components/LoginRegistration/Registration.js

I didn't end up keeping the CssBaseline because it caused some issues with settings made earlier in index.html.  I made some tweeks so that the login and registration backgrounds cover the full width and height of the screen.

set css baselines

---

src/Components/App.js

This is a judgement call.  The biggest difference is the change in the background color

removed CssBaseline component

---

src/ActionCreators/actions.js
src/Reducers/UsersReducer.js

This allows the logged in user profile to update when the user updates their information

connected updateUser action creator to UsersReducer

---

src/ActionCreators/actions.js

This results in a complete users object prior to page load.

changed logInUser() to call getUsers() before dispatching LOGIN_USER action

---

src/Components/Profile.js

This changes the size of the user image so that it is contained inside its parent component

Image contain

---

src/Components/Profile.js

There is a bit of a hiccup on load, but this prevents the condition where there is a large space allocated for a comparatively smaller image.

profile image container resizes to match height of image

---

package.json
src/index.js

corrected homepage in package.json

Routing basename
